services:
  - type: web
    name: marks-calculator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn marks_calculator.wsgi:application --log-file -
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: marks-db
          property: connectionString
databases:
  - name: marks-db
    plan: free
